### PR TITLE
Bear Trap and Powershot Implementations

### PR DESCRIPTION
**Pull request by AlexSafatli**
Still need to consider tests for when board is filled for *Snake Trap* and *Bear Trap*. For the time being, these are simply two tests written to more or less emulate the tests for *Snake Trap* and *Explosive Shot* respectively.

### CODE REVIEW

**Comment by danielyule** [comment]
The reason it was failing is because the code wasn't up to pep8 formatting standards.  Travis runs an automatic check.  You can check yourself using flake8, or by enabling pep8 checks in your code editor if it supports it (I think all the major ones do, perhaps via plugins).

It's still broken because I'm bad at git and accidentally merged in my broken code for a work in progress.

**Comment by AlexSafatli** [comment]
Ah, alright. I'll check it out.

**Comment by AlexSafatli** [comment]
Looks like a lot of lines are too long. Is that something travis is checking as well? In that case, it was not just the code I committed.

**Comment by danielyule** [comment]
If you look at setup.cfg, you can see I've changed the line length from 80 to 120 on the theory that monitors are way bigger than they were when the 80 limit was decided on.  I think everything should fit within that.

**Pull request merged**
