### PR TITLE
add king of beasts

### PR DESCRIPTION
**Pull request by zetsubo**

### CODE REVIEW

**Comment by danielyule** [comment]
This is failing, but that's due to a bug in one of my tests, which has been fixed on the master.  A larger concern (and this isn't really documented anywhere, so what you did was quite reasonable) is that it uses the old battlecry system, where they were implemented directly as python code, and not using the new system where they are declared.  It's a bit more complicated, but have a look at Old Murk Eye's battlecry for an example of what I'm talking about.  If you have any questions, feel free to ask and I will try to explain what's going on.  I admit it's a bit complicated, and (as I mentioned before) undocumented.

**Comment by zetsubo** [comment]
Thanks! I'll rebase and fix the battlecry in a bit.

**Comment by danielyule** [comment]
I completely forgot about this PR, or I would have updated it with info about how to implement it, rather than doing it myself!  Apologies.

**Comment by zetsubo** [comment]
nah it's cool, I got really busy with work and didn't come back to it. The PR died when I reset my branch to your master last night to work on another pull request :)

**Pull request closed without merging**
